resources:
  - default-deny.yaml
  - allow-dns.yaml
  - allow-app-to-postgres.yaml
  - allow-flyway-egress-to-postgres.yaml
  - allow-postgres-from-flyway.yaml
  - allow-student-reg-egress-to-postgres.yaml
  - allow-student-reg-from-ingress-nginx.yaml
  - allow-student-reg-from-prometheus.yaml
