apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    argocd.argoproj.io/tracking-id: platform-ingress:networking.k8s.io/Ingress:monitoring/alertmanager
spec:
  ingressClassName: nginx
  rules:
    - host: alertmanager.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prom-stack-kube-prome-alertmanager
                port:
                  number: 9093
