resources:
  - ../../base
  - ingress.yaml
  - namespace.yaml

namespace: student-reg-prod

images:
  - name: ghcr.io/min2max-m/student-reg
    newName: ghcr.io/min2max-m/student-reg
    newTag: sha-1d0d1d7
