resources:
  - ../../base
  - ingress.yaml

namespace: student-reg-prod

images:
  - name: ghcr.io/min2max-m/student-reg
    newName: ghcr.io/min2max-m/student-reg
    newTag: sha-c96d3ed

patches:
  - path: namespace-patch.yaml
