resources:
  - ../../base

namespace: student-reg-staging

images:
  - name: ghcr.io/min2max-m/student-reg
    newName: ghcr.io/min2max-m/student-reg
    newTag: sha-1d0d1d7

patches:
  - path: namespace-patch.yaml
