resources:
  - flyway-sa.yaml
  - job.yaml

configMapGenerator:
  - name: flyway-migrations
    files:
      - migrations/V1__create_students.sql
      - migrations/V2__updated_at_trigger.sql

generatorOptions:
  disableNameSuffixHash: true
