resources:
  - ../../base
  - ingress.yaml

namespace: student-reg-dev

images:
  - name: ghcr.io/min2max-m/student-reg
    newName: ghcr.io/min2max-m/student-reg
    newTag: sha-14b5848

patches:
  - path: namespace-patch.yaml
