apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: student-reg
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - student-reg-dev
  selector:
    matchLabels:
      app: student-reg
  endpoints:
    - port: http
      path: /metrics
      interval: 15s